// import './src/ex.1.schema-model-create/index1.mjs'
// import './src/ex.2.scheme-options/index1.mjs'
// import './src/ex.3.find/index1.mjs'
// import './src/ex.4.cursor/index1.mjs'
// import './src/ex.5.aggregation-pipeline/index1.mjs'
// import './src/ex.6.update-delete-replace/index1.mjs'
// import './src/ex.7.virtuals/index1.mjs'
// import './src/ex.8.indexes/index1.mjs'
// import './src/ex.9.populate/index1.mjs'
// import './src/ex.10.validators/index1.mjs'
import './src/ex.11.middlewares/index6.mjs'
